### ISSUE TITLE
[BUG] 로비 화면 빨간 점 오류

### ISSUE THREAD

**Issue by ssssssssssvsc** [Geniards/Unity_Team_Project#66]
- 버그 리포트
    - 버그 개요 : 로비 화면에서 클릭해야할 버튼 위에 빨간 점이 존재해 클릭해야할 UI의 면적을 줄임 
    - 상황 재연 : 버그가 일어난 상황을 가능한 수준에서 단계별로 설명
    - 참고 자료 : 
![화면 캡처 2024-11-04 174457](https://github.com/user-attachments/assets/085f730e-922a-49ef-93c6-53df1558b683)
![화면 캡처 2024-11-04 174520](https://github.com/user-attachments/assets/bc214ba5-55a4-48fb-83e5-c8d5659bbfdc)

    - 구동 환경 :
    - 발견 일시 : 2024.11.04
    - 요청 내용 : 해당 버그를 어떻게 수정해야 하는지 요청 사항을 기입
    - 추가 코멘트 : 추가로 적을 내용. 추신.

**Comment by karrk** [comment]
처리 일시 : 2024.11.04

처리 내역 : 해당 씬 폴리싱 과정 중 빌드 파일 요청으로 인한 기능 오류입니다.
현재 처리 완료되었습니다.

**Comment by ssssssssssvsc** [comment]
감사합니다.
