### ISSUE TITLE
[BUG] 스테이지 3 보스 격돌 지속 현상

### ISSUE THREAD

**Issue by minggu27** [Geniards/Unity_Team_Project#68]
- 버그 리포트
    - 버그 개요 : 스테이지 3 보스 격돌 지속 현상
    - 상황 재연 : 기존에 노트가 판정원에 위치해 있는 버그가 존재한 채로 진행했습니다. 다수 플레이 해 본 결과 버그가 2번 관측되었습니다. 둘 다 버그가 위와 같은 상황에서(혹은 기존에 다른 버그가 존재 한 채로 플레이 했을 때) 현상이 나타났습니다.
    - 참고 자료 : https://drive.google.com/file/d/1ZqkcJPcAo0wBq9xftwwQxuCQNvtqG4Pq/view?usp=drive_link
    - 구동 환경 : Window
    - 발견 일시 : 2024.11.04
    - 요청 내용 : 해당 버그를 어떻게 수정해야 하는지 요청 사항을 기입
    - 추가 코멘트 : 추가로 적을 내용. 추신.

**Comment by minggu27** [comment]
홈으로 돌아갔다가 다시 스테이지에 진입하면 버그가 발생하는 것 같습니다.
참고자료 : https://drive.google.com/file/d/1fwbmzTLUMLTuowNDqCSlW87IIjFvlixk/view?usp=sharing

**Comment by karrk** [comment]
내부 기능문제로 발생된 버그입니다. 현재 내부 구조 수정으로 인해 해결되었습니다.
