### ISSUE TITLE
[BUG] 스테이지 클리어 후 점수가 증가하는 버그

### ISSUE THREAD

**Issue by minggu27** [Geniards/Unity_Team_Project#74]
- 버그 리포트
    - 버그 개요 : 보스 처치 후 스테이지 클리어로 넘어가지 않고 점수가 증가함.
    - 상황 재연 : 스테이지 1 클리어 후, 홈으로 돌아갔다 재 입장 후 플레이.
    - 참고 자료 : https://drive.google.com/file/d/1RUWTjtFYdPhvMCLtX4IGmR3pRQ40C69T/view?usp=sharing
    - 구동 환경 : Window
    - 발견 일시 : 2024.11.04
    - 요청 내용 : 해당 버그를 어떻게 수정해야 하는지 요청 사항을 기입
    - 추가 코멘트 : 추가로 적을 내용. 추신.

**Comment by karrk** [comment]
기능 구현중 QA가 진행되어 미흡한 기능입니다.
현재 시점 11월 06일 해당 문제점 해결되었습니다.
